### ISSUE TITLE
Frage zu Wotexx...

### ISSUE THREAD

**Issue by skydive241** [seanox/xml-online-storage#1]
Hi!

Ich habe eigentlich eine Frage zu einem alten Projekt, zu Wotexx, um genau zu sein, finde aber keinen besseren Weg, um mich bemerkbar zu machen, als hier eine Issue zu erfassen.

Falls Sie mir zu Wotexx etwas beantworten möchten, würde ich mich freuen, wenn Sie mir eventuell eine Mail an skydive241@gmx.de schreiben.

Vorab danke und Gruß
Patrick

**Comment by seanox** [comment]
Hallo Patrick,
bei sonstigen Fragen, auch zu Projekten die nicht mehr existieren, kannst Du den Mail-Link https://seanox.de/contact verwenden, der am Ende jeder Projektseite im Abschnitt "Contact" steht.

//

For other questions, even about projects that no longer exist, you can use the mail link https://seanox.de/contact at the bottom of each project page in the "Contact" section,

Viele Grüsse,
Seanox

**Comment by skydive241** [comment]
Leider wird meine Antwort sowohl an o...@sean..., als auch an Serv...@sean... als Spam abgelehnt...., deshalb muss ich leider doch hier antworten:

Hi,Oliver, und erstmal danke für Ihre Antwort!

Ja, WoTexx wird noch verwendet - um genau zu sein, habe ich es vor Jahren sehr gerne verwendet, um meine beruflichen und privaten Projekte zu dokumentieren, und zwar hauptsächlich, weil ich den eingebauten Editor klasse fand. Als das dann leider mit neueren Browserversionen nicht mehr funktionierte, habe ich dann irgendwann auf ein anderes Tool gewechselt.

Aus irgendeinem Grund bin ich aber unlängst mal wieder auf WoTexx gekommen und fand es einfach schade, dass ich es damals völlig aus dem Blick verloren habe. Ich habe jetzt einfach mal getestet, bis zu welcher Firefox-Version der eingebaute Editor funktioniert hatte (Version 14) und mir die Frage gestellt, ob ich den aus Ihrer WoTexx-Version1.2014.0731 ausgebauten Editor wieder einbauen kann (aus Version 1.2011.0226 übernehmen). Dabei habe ich mir natürlich auch die (naheliegende) Frage gestellt, ob Sie den Code der verschiedenen Versionen inklusive Build-Scripte noch haben und mir eventuell zur Verfügung stellen oder einfach wieder bei Github veröffentlichen würden ....

Das war in etwa die Frage, die ich stellen wollte. Den Link am Ende der Seite hatte ich durchaus wahrgenommen, aber ich habe auf meinem Rechner kein Mailprogramm installiert, sondern nutze fast immer Google. Okay, inzwischen habe ich "ge-curl-t", dass die Adresse [service@seanox.de](mailto:service@seanox.de) dahintersteckt, hätte also auch dahin schreiben können. :)

Gruß
Patrick

**Comment by skydive241** [comment]
Anfragen an Ihre Service-E-Mail-Adresse werden leider generell als Spam verworfen.

Gruß
Patrick
